// flow-typed signature: 9e3fdf10abf1e11fa9c76b5290f69c99
// flow-typed version: <<STUB>>/eslint-config-unobtrusive_v^1.2.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-unobtrusive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-unobtrusive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-unobtrusive/flowtype' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/import' {
  declare module.exports: any;
}

declare module 'eslint-config-unobtrusive/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-unobtrusive/flowtype.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/flowtype'>;
}
declare module 'eslint-config-unobtrusive/import.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/import'>;
}
declare module 'eslint-config-unobtrusive/index' {
  declare module.exports: $Exports<'eslint-config-unobtrusive'>;
}
declare module 'eslint-config-unobtrusive/index.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive'>;
}
declare module 'eslint-config-unobtrusive/react.js' {
  declare module.exports: $Exports<'eslint-config-unobtrusive/react'>;
}
