// flow-typed signature: 3608db34a399bcf896f655d7266300f7
// flow-typed version: <<STUB>>/github-webhook-handler_v^0.7.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github-webhook-handler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'github-webhook-handler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'github-webhook-handler/github-webhook-handler' {
  declare module.exports: any;
}

declare module 'github-webhook-handler/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'github-webhook-handler/github-webhook-handler.js' {
  declare module.exports: $Exports<'github-webhook-handler/github-webhook-handler'>;
}
declare module 'github-webhook-handler/test.js' {
  declare module.exports: $Exports<'github-webhook-handler/test'>;
}
