// flow-typed signature: e67c986695eba857dd9fc08249ec9f7f
// flow-typed version: <<STUB>>/github-app_v^3.2.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'github-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'github-app/docs/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'github-app/docs/example.js' {
  declare module.exports: $Exports<'github-app/docs/example'>;
}
declare module 'github-app/index' {
  declare module.exports: $Exports<'github-app'>;
}
declare module 'github-app/index.js' {
  declare module.exports: $Exports<'github-app'>;
}
